version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mydockernet
    volumes:
      - app_mongo:/data/db
  appserver:
    container_name: appserver
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mydockernet
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=appdb
    depends_on:
      - mongo
  appclient:
    container_name: appclient
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mydockernet
    environment:
      - NODE_ENV=dev
      - REACT_APP_API_URL=http://apiserver:5000
    volumes: # For webpack dev server to use our local files
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - appserver
networks:
  mydockernet:
    driver: bridge
volumes:
  app_mongo:
